# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nodekube-service
spec:
  selector:
    app: nodejs-kube-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
